
public enum ObjectId
{
    COAL = 0,
    STONE = 1,
    BASALT = 2,
    MARBLE = 3,

    COPPER = 10,
    IRON = 11,
    SILVER = 12,
    PLATINUM = 13,
    ADAMANTITE = 14,
    MITHRIL = 15,

    GOLD = 20,
    EMERALD = 21,
    RUBY = 22,
    SAPPHIRE = 23,

    STONE_PICKAXE = 50,

    COAL_CHEST_KEY = 100,
    STONE_CHEST_KEY = 101,
    BASALT_CHEST_KEY = 102,
    MARBLE_CHEST_KEY = 103,

    COPPER_CHEST_KEY = 110,
    IRON_CHEST_KEY = 111,
    SILVER_CHEST_KEY = 112,
    PLATINUM_CHEST_KEY = 113,
    ADAMANTITE_CHEST_KEY = 114,
    MITHRIL_CHEST_KEY = 115,

    GOLD_CHEST_KEY = 120,
    EMERALD_CHEST_KEY = 121,
    RUBY_CHEST_KEY = 122,
    SAPPHIRE_CHEST_KEY = 123,
}
